export const REPORT_TYPES = [
  'USER_REGISTRATIONS',
  'USER_ACCOUNT_STATUS',
  'COURSE_ENROLLMENTS',
  'COURSE_PARTICIPATION',
  'LEARNING_PROGRESS',
  'COURSE_COMPLETIONS',
  'PAYMENTS',
  'REVENUE',
  'PAYMENT_REVIEW_PERFORMANCE',
  'CERTIFICATES',
  'CERTIFICATE_GENERATION',
  'ADMINISTRATOR_ACTIVITY',
  'AUTHENTICATION_SECURITY_EVENTS',
] as const;
export type ReportType = (typeof REPORT_TYPES)[number];
export type ReportFormat = 'CSV' | 'XLSX' | 'PDF';
