/**
 * Central route path constants. Prefer these over hardcoded string literals
 * so a path change only needs to happen in one place - notably the same
 * `/auth`, `/admin`, `/dashboard` segments enforced by `src/middleware.ts`.
 */
export const ROUTES = {
  home: '/',
  health: '/health',
  forbidden: '/403',
  about: '/about',
  pricing: '/pricing',
  contact: '/contact',
  faq: '/faq',
  helpCenter: '/help-center',
  privacyPolicy: '/privacy-policy',
  terms: '/terms',
  cookiePolicy: '/cookie-policy',
  instructors: {
    list: '/instructors',
    detail: (slug: string) => `/instructors/${slug}`,
  },
  courses: {
    list: '/courses',
    detail: (slug: string) => `/courses/${slug}`,
  },
  categories: {
    list: '/categories',
    detail: (slug: string) => `/categories/${slug}`,
  },
  certificates: {
    verify: (token: string) => `/certificates/verify/${token}`,
    verifyLookup: '/certificates/verify',
  },
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyEmail: '/auth/verify-email',
    googleCallback: '/auth/google/callback',
  },
  dashboard: {
    root: '/dashboard',
    browseCourses: '/dashboard/browse-courses',
    courseDetail: (slug: string) => `/dashboard/browse-courses/${slug}`,
    courses: '/dashboard/courses',
    wishlist: '/dashboard/wishlist',
    checkout: '/dashboard/checkout',
    certificates: '/dashboard/certificates',
    certificateDetail: (id: string) => `/dashboard/certificates/${id}`,
    verifyCertificate: '/dashboard/verify-certificate',
    learn: (enrollmentId: string) => `/dashboard/courses/${enrollmentId}/learn`,
    payments: '/dashboard/payments',
    notifications: '/dashboard/notifications',
    support: '/dashboard/support',
    profile: '/dashboard/profile',
    security: '/dashboard/security',
  },
  admin: {
    root: '/admin/dashboard',
    users: '/admin/users',
    userDetail: (userId: string) => `/admin/users/${userId}`,
    userEdit: (userId: string) => `/admin/users/${userId}/edit`,
    academics: '/admin/academics',
    academicsCourses: '/admin/academics/courses',
    academicsCourseCreate: '/admin/academics/courses/create',
    academicsCourseDetail: (courseId: string) => `/admin/academics/courses/${courseId}`,
    academicsCourseEdit: (courseId: string) => `/admin/academics/courses/${courseId}/edit`,
    academicsCourseCurriculum: (courseId: string) =>
      `/admin/academics/courses/${courseId}/curriculum`,
    academicsCourseLesson: (courseId: string, lessonId: string) =>
      `/admin/academics/courses/${courseId}/lessons/${lessonId}`,
    academicsCategories: '/admin/academics/categories',
    academicsCategoryCreate: '/admin/academics/categories/create',
    academicsCategoryDetail: (categoryId: string) => `/admin/academics/categories/${categoryId}`,
    academicsCategoryEdit: (categoryId: string) => `/admin/academics/categories/${categoryId}/edit`,
    academicsInstructors: '/admin/academics/instructors',
    academicsEnrollments: '/admin/academics/enrollments',
    financial: '/admin/financial',
    financialPayments: '/admin/financial/payments',
    financialPromoCodes: '/admin/financial/promo-codes',
    financialPromoCodeDetail: (codeId: string) => `/admin/financial/promo-codes/${codeId}`,
    certificates: '/admin/certificates',
    certificateDetail: (certificateId: string) => `/admin/certificates/${certificateId}`,
    verifyCertificate: '/admin/verify-certificate',
    communication: '/admin/communication',
    communicationNotifications: '/admin/communication/notifications',
    communicationEmailTemplates: '/admin/communication/email-templates',
    communicationEmailTemplateDetail: (templateId: string) =>
      `/admin/communication/email-templates/${templateId}`,
    communicationSupport: '/admin/communication/support',
    reports: '/admin/reports',
    analytics: '/admin/reports/analytics',
    system: '/admin/system',
    systemRoles: '/admin/system/roles',
    systemRoleCreate: '/admin/system/roles/create',
    systemRoleDetail: (roleId: string) => `/admin/system/roles/${roleId}`,
    systemRoleEdit: (roleId: string) => `/admin/system/roles/${roleId}/edit`,
    systemPermissions: '/admin/system/permissions',
    systemActivityLogs: '/admin/system/activity-logs',
    systemAcademySettings: '/admin/system/academy-settings',
    systemProfile: '/admin/system/profile',
    systemSecurity: '/admin/system/security',
  },
} as const;
