export { PageHeaderSkeleton } from './page-header-skeleton';
export { BreadcrumbSkeleton } from './breadcrumb-skeleton';
export { HeroSkeleton } from './hero-skeleton';
export { NumberedStepsSkeleton } from './numbered-steps-skeleton';
export { StatsBandSkeleton } from './stats-band-skeleton';
export { CtaBannerSkeleton } from './cta-banner-skeleton';
export { SectionPlaceholderSkeleton } from './section-placeholder-skeleton';
export { InstructorCardSkeleton, InstructorGridSkeleton } from './instructor-card-skeleton';
export { CourseDetailSkeleton } from './course-detail-skeleton';
export { CategoryDetailSkeleton } from './category-detail-skeleton';
export { InstructorDetailSkeleton } from './instructor-detail-skeleton';
export { PricingPageSkeleton } from './pricing-page-skeleton';
export { HomePageSkeleton } from './home-page-skeleton';
export { AboutPageSkeleton } from './about-page-skeleton';
