export const PERMISSION_CODES = [
  'permissions.read',
  'roles.read',
  'roles.create',
  'roles.update',
  'roles.archive',
  'roles.assign_permissions',
  'roles.assign_users',
  'roles.remove_users',
  'users.read',
  'users.update',
  'users.activate',
  'users.suspend',
  'users.archive',
  'users.view_sessions',
  'users.revoke_sessions',
  'users.assign_roles',
  'categories.read',
  'categories.create',
  'categories.update',
  'categories.archive',
  'courses.read',
  'courses.create',
  'courses.update',
  'courses.publish',
  'courses.unpublish',
  'courses.archive',
  'courses.duplicate',
  'lessons.read',
  'lessons.create',
  'lessons.update',
  'lessons.reorder',
  'lessons.publish',
  'lessons.archive',
  'enrollments.read',
  'enrollments.update',
  'enrollments.cancel',
  'enrollments.revoke',
  'payments.read',
  'payments.approve',
  'payments.decline',
  'certificates.read',
  'certificates.generate',
  'certificates.regenerate',
  'certificates.revoke',
  'reports.read',
  'reports.export',
  'audit.read',
  'settings.read',
  'settings.update',
] as const;
export type PermissionCode = (typeof PERMISSION_CODES)[number];
export const permissionSeed = PERMISSION_CODES.map((code) => ({
  code,
  module: code.split('.')[0] ?? 'system',
  description: code
    .split('.')
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join(' '),
}));
